### ISSUE TITLE
Can't Harvest Cherries.

### ISSUE THREAD

**Issue by fastoo123** [Erdragh/Astral-Vinery#11]
Whenever I grow cherry trees and try to right click the leaves with the red cherries on them, it doesn't do anything. When I chop the tree down, it rarely drops cherries. I'd appreciate any help. This involves the Vinery mod.

**Comment by Erdragh** [comment]
1. This is not an _AstralVinery_ specific issue, it's a _Vinery_ issue.
2. That's intended. You harvest cherries by right clicking the leaves with shears

**Comment by fastoo123** [comment]
Oh thanks!! I was trying really hard to figure out how to figure this out.
