### ISSUE TITLE
unnamed categories

### ISSUE THREAD

**Issue by AnAwesomGuy** [Erdragh/Astral-Vinery#4]
![image](https://user-images.githubusercontent.com/79700396/226230740-ad0b3a23-fd2f-4aba-8411-e1af35405c28.png)

**Comment by AnAwesomGuy** [comment]
also, how do i build this repo?

**Comment by Erdragh** [comment]
> also, how do i build this repo?

Should be just
```
./gradlew build
```

I use IntelliJ, which auto imports the gradle tasks so I can run them from the IDE. I also have the Minecraft extension installed for IntelliJ

**Comment by Erdragh** [comment]
https://fabricmc.net/wiki/tutorial:setup
