### ISSUE TITLE
1.19.2 port?

### ISSUE THREAD

**Issue by lostopkk** [Erdragh/Astral-Vinery#7]
just asking...

**Comment by Erdragh** [comment]
The two major points this Mod does is fixing two bugs that don't exist in the 1.19 version of Vinery. I assume you want the fix for the Schematicannon?

**Comment by lostopkk** [comment]
> 

Sorry if this question pissed you off as much as the creator, I don't want to disrespect them for the great work they do, I just wanted to know if it might take a while or if there will ever be a time for the release. I'm sorry if this issue seemed like something to piss you off, it wasn't my intention.

**Comment by Erdragh** [comment]
No you didn't piss me off, everything is fine, I just wanted to know what part of the mod you wanted to be ported to 1.19, because all this mod does is fix some issues with Vinery, that are already fixed in Vinery's new versions. This is not the repository for Vinery.

**Comment by lostopkk** [comment]
Now that I understand what you mean, I'm sorry. didn't know this was just something to fix, thought there were new mechanics that work between these two mods

**Comment by Erdragh** [comment]
Well I'm just gonna say, _not yet_

**Comment by Erdragh** [comment]
Closing, as the misunderstanding was cleared up

**Comment by lostopkk** [comment]
Interesting what you said, but thank you for having the patience to answer me for what I did. does a great job, congrats.
